### ISSUE TITLE
Better wording for process boundary

### ISSUE THREAD

**Issue by shhnjk** [mikewest/post-spectre-webdev#5]
> This revelation has pushed web browsers to shift their focus from the platform-level origin boundary to a hardware-level process boundary.

I think it's more accurate to say `OS-level process boundary` instead of `hardware-level process boundary`.

**Comment by shhnjk** [comment]
Also, there is a typo: `We m)ust design accordingly`.

**Comment by mikewest** [comment]
Thanks! Fixed in https://github.com/mikewest/post-spectre-webdev/commit/eea6a15dec8c901953475ce68e0c899cb702d5db
