### ISSUE TITLE
What do you mean by this?

### ISSUE THREAD

**Issue by shhnjk** [mikewest/post-spectre-webdev#6]
> User agents are capable of segregating the execution of attacker-provided code from the agent’s core. That is, it remains possible for the agent to take actions which are not associated with any given origin, and for those actions to remain invisible to every origin.

What you want to tell to developers in above sentence is unclear to me.

Also, should I file these kind of questions in issues, or is there a word doc where I can comment?

**Comment by mikewest** [comment]
I put up #10 to make this a little more clear. WDYT?

**Comment by shhnjk** [comment]
LGTM :)
