### ISSUE TITLE
Try asking for requesting CORS for default no-cors subresources?

### ISSUE THREAD

**Issue by shhnjk** [mikewest/post-spectre-webdev#7]
> Personalized resources that are intended for cross-origin no-cors embedding, but which don’t intend to be directly legible in that context (avatar images, authenticated media, etc). These should enable cross-origin embedding via Cross-Origin-Resource-Policy, but _not_ via CORS access control headers:

Before allowing them to open up, maybe we should ask them to try out `crossorigin="use-credentials"`?

**Comment by mikewest** [comment]
The claim here is that it's better to allow embedding via CORP than CORS, as CORS exposes the resources' bits directly, while CORP requires the attacker to perform an attack in order to read the bits. Basically, it defends against honest-but-curious embedders.

/cc @arturjanc, who had some opinions about this division.

**Comment by arturjanc** [comment]
I wrote down a few reasons why CORP seems better than CORS for such resources in the [COI threat model](https://docs.google.com/document/d/1JBUaX1xSOZRxBk5bRNZWgnzyJoCQC52TIRokACBSmGc/edit#heading=h.u7mkumxt1zx1).

Basically, a web where authenticated `no-cors` resources are CORS-enabled seems scarier to me than a web where such resources opt into embedding via CORP. After all, we may get better CPUs one day, or browsers may start rendering images in a separate process; and even if not, it's not unreasonable that browser or OS-level mitigations may complicate, or reduce the bandwidth of, Spectre-based attacks. If we recommend CORS, we pretty much give up on protecting such resources.

**Comment by shhnjk** [comment]
Sorry, I didn't explain in details :D What I was suggesting is, why don't we tell developers to try CORS with specific origins? Since this is a personalized resource, it's possible that the resource is only intended for certain origins. In that case, they can securely expose such resource using CORS, instead of exposing to all cross-origin sites using CORP.

**Comment by shhnjk** [comment]
Okay, my bad. You guys are suggesting that `CORP: cross-origin` is better than `CORS: <origin>`. That's... surprising :D 

I've read the Artur's point on the doc, but I have 2 points to make.

First, It's seems reasonable for a site to return `CORP: cross-origin` if they want to allow many sites to obtain personalized response. However, if a site only wants to serve a site or two (and assuming that those sites are trustworthy), then I think it does make sense to serve `CORS: <origin>` instead. My view is that we should at least provide this as an option in the doc, instead of giving developers the only option of `CORP: cross-origin`, which allows an attacker to obtain data using precise timers.

Second, when we support credentialless mode, we basically block these developers where we told them to use `CORP: cross-origin`. While removing third-party cookie might block them faster, this is an important consideration to have, as we might need to change the message in the future.

Given above, I think it's reasonable to provide `CORS: <origin>` as an option for personalized resources against no-cors requests.

**Comment by mikewest** [comment]
It's a trade-off along a different axis. That is, `CORS: <origin>` allows the personalized resource to be embedded in one specific place, _and also_ allows that place to trivially access its bits. `CORP: cross-origin` allows the personalized resource to be embedded anywhere, but doesn't allow trivial access to its bits. That might be the right tradeoff sometimes, and it's certainly worth putting in a note, but I'm not sure it's "safe" in any deep sense for these kinds of resources.

(Tangentially, I still think we ought to build some CORP-based origin binding (along the lines of https://github.com/whatwg/fetch/issues/760, probably in combination with https://github.com/mikewest/resource-policy) to allow CORP more granularity. That would be the right thing to recommend here, I think.)

**Comment by shhnjk** [comment]
> but I'm not sure it's "safe" in any deep sense for these kinds of resources.

For example, let's imagine that YouTube.com serves a private video content, and Google.com has a tool that can add an effect to it online. In this scenario, YouTube only wants to expose private video of user to Google, so that it can be edited there and have a preview. If YouTube does this today with `CORP: cross-origin`, I would report that as a security bug to Google, and I would imagine it'll get fixed using CORS.

My view is that cross-origin doesn't always mean different parties. And therefore it would sometimes makes sense to use CORS.

>(Tangentially, I still think we ought to build some CORP-based origin binding (along the lines of whatwg/fetch#760, probably in combination with https://github.com/mikewest/resource-policy) to allow CORP more granularity. That would be the right thing to recommend here, I think.)

Makes sense :)

**Comment by mikewest** [comment]
I'll add a note to that effect, thanks!
