### ISSUE TITLE
Is there any benefit on explicitly setting default headers?

### ISSUE THREAD

**Issue by shhnjk** [mikewest/post-spectre-webdev#8]
> X-Frame-Options: ALLOWALL
> Cross-Origin-Opener-Policy: unsafe-none

Is there any benefit on setting these? If so, maybe add an explanation?

**Comment by mikewest** [comment]
The core benefit is that it would enable us to more easily change the default (along the lines of https://github.com/mikewest/embedding-requires-opt-in). I'll add a note.
