### ISSUE TITLE
Maybe add a note about cross-origin isolation

### ISSUE THREAD

**Issue by shhnjk** [mikewest/post-spectre-webdev#9]
Web security has been in an interesting ride. And whenever we introduced new security features, we gave a tools for **trusted** sites to protect themselves from attackers (CSP, fetch medata, etc).

However, cross-origin isolation is a security feature, in which we are saying that "**We don't trust you, so all resources you load needs a consent**".

I think this needs to be emphasized in the document. Because the naming of cross-origin isolation _sounds_ like we are giving a tool to isolate a secure website from untrusted sites (which isn't the case).

This is an important point to make, as if COI context loads an ad that consent to be embedded, they can read data of COI context document per the following threat model.

>With this in mind, our general assumption will be that an origin gains access to any resource which it renders (including images, stylesheets, scripts, frames, etc). Likewise, embedded frames gain access to their ancestors' content.

**Comment by mikewest** [comment]
I think it's pretty reasonable to talk about COI as a set of restrictions that we want to put in place, but the story is complicated. COOP feels like it's both a necessary restriction _and_ directly beneficial to the developer asserting it (by breaking attackers' window handles). COEP is more clearly restrictive; no one's going to opt-into that unless we make them.

Do you have a suggestion for framing this more explicitly?

**Comment by shhnjk** [comment]
Maybe make a section (in implementation considerations?) where we explain differences between `Fully-Isolated Documents` and `Cross-Origin Isolated Documents`? We can move the note about SharedArrayBuffer requiring COI there as well.
